export const TECHNICIAN_HEADERS = [
	"Timestamp",
	"First Name",
	"Last Name",
	"City",
	"State",
	"Certificate #",
	"Birthdate",
	"Phone #",
	"Email",
	"Certification Level",
	"Core Date",
	"Type 1 Date",
	"Type 2 Date",
	"Type 3 Date",
	"General Date",
	"Website Found",
];

export const DUMMY_DATA = [
	{
		Timestamp: "2021-09-01T00:00:00.000Z",
		"First Name": "John",
		"Last Name": "Doe",
		City: "New York",
		State: "NY",
		"Certificate #": "123",
		Birthdate: "01/01/1990",
		"Phone #": "123-456-7890",
		Email: "test@gmail.com",
		"Certification Level": "Type 1",
		"Core Date": "01/01/2020",
		"Type 1 Date": "01/01/2020",
		"Type 2 Date": "01/01/2020",
		"Type 3 Date": "01/01/2020",
		"General Date": "01/01/2020",
		"Website Found": "Google",
	},
	{
		Timestamp: "2021-09-01T00:00:00.000Z",
		"First Name": "John",
		"Last Name": "Doe",
		City: "New York",
		State: "NY",
		"Certificate #": "123",
		Birthdate: "01/01/1990",
		"Phone #": "123-456-7890",
		Email: "test@gmail.com",
		"Certification Level": "Type 1",
		"Core Date": "01/01/2020",
		"Type 1 Date": "01/01/2020",
		"Type 2 Date": "01/01/2020",
		"Type 3 Date": "01/01/2020",
		"General Date": "01/01/2020",
		"Website Found": "Google",
	},
];

export const states = {
	Alabama: "AL",
	Alaska: "AK",
	Arizona: "AZ",
	Arkansas: "AR",
	California: "CA",
	Colorado: "CO",
	Connecticut: "CT",
	Delaware: "DE",
	"District of Columbia": "DC",
	Florida: "FL",
	Georgia: "GA",
	Hawaii: "HI",
	Idaho: "ID",
	Illinois: "IL",
	Indiana: "IN",
	Iowa: "IA",
	Kansas: "KS",
	Kentucky: "KY",
	Louisiana: "LA",
	Maine: "ME",
	Maryland: "MD",
	Massachusetts: "MA",
	Michigan: "MI",
	Minnesota: "MN",
	Mississippi: "MS",
	Missouri: "MO",
	Montana: "MT",
	Nebraska: "NE",
	Nevada: "NV",
	"New Hampshire": "NH",
	"New Jersey": "NJ",
	"New Mexico": "NM",
	"New York": "NY",
	"North Carolina": "NC",
	"North Dakota": "ND",
	Ohio: "OH",
	Oklahoma: "OK",
	Oregon: "OR",
	Pennsylvania: "PA",
	"Rhode Island": "RI",
	"South Carolina": "SC",
	"South Dakota": "SD",
	Tennessee: "TN",
	Texas: "TX",
	Utah: "UT",
	Vermont: "VT",
	Virginia: "VA",
	Washington: "WA",
	"West Virginia": "WV",
	Wisconsin: "WI",
	Wyoming: "WY",
};
